version: '3.7'

x-container-common: &container-common
  restart: ${CONTAINER_RESTART-on-failure}
  networks:
    - orchestrate

services:
  zookeeper:
    <<: *container-common
    image: confluentinc/cp-zookeeper:5.3.0
    ports:
      - ${ZOOKEEPER_EXTERNAL_PORT-2181}:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT-32181}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME-2000}

  kafka:
    <<: *container-common
    image: confluentinc/cp-kafka:5.3.0
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_EXTERNAL_PORT-9092}:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT-32181}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${KAFKA_EXTERNAL_HOSTNAME-localhost}:${KAFKA_EXTERNAL_PORT-9092}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  redis:
    <<: *container-common
    image: redis:5.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports: 
      - 6379:6379
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf

  postgres-contract-registry:
    <<: *container-common
    image: postgres:10-alpine
    ports:
      - 5432
    volumes:
      - db-data-contract-registry:/var/lib/postgresql/data

  postgres-envelope-store:
    <<: *container-common
    image: postgres:10-alpine
    ports:
      - 5432
    volumes:
      - db-data-envelope-store:/var/lib/postgresql/data
  
  geth:
    <<: *container-common
    image: ethereum/client-go:v1.9.0
    ports:
      - 8545:8545
    entrypoint:
      - /bin/sh
      - -c
      - |
        geth --datadir "/nodeData" init "/nodeData/genesis.json"
        geth \
        --rpc \
        --rpcaddr "0.0.0.0" \
        --rpcport "${GETH_RPC_PORT-8545}" \
        --rpccorsdomain "*" \
        --rpcvhosts "*" \
        --datadir "/nodeData" \
        --port "${GETH_PORT-30303}" \
        --rpcapi "admin,eth,net,web3,personal,txpool" \
        --networkid ${GETH_NETWORKID-888} \
        --nodiscover \
        --unlock "0" \
        --password "/nodeData/password" \
        --allow-insecure-unlock \
        --mine \
        --debug \
        --ipcdisable \
        --syncmode "full"
    volumes:
      - ./config/geth/genesis.json:/nodeData/genesis.json
      - ./config/geth/keystore:/nodeData/keystore
      - ./config/geth/password:/nodeData/password
      - chain-data:/nodeData/geth

  vault:
    <<: *container-common
    image: library/vault:1.1.1
    tty: true
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config/hashicorp/config.hcl:/vault/config.hcl:ro
    entrypoint: vault server -config=/vault

  jaeger:
    <<: *container-common
    image: jaegertracing/all-in-one:1.8
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411


volumes:
  db-data-contract-registry:
    driver: local
  db-data-envelope-store:
    driver: local
  chain-data:
    driver: local


networks:
  orchestrate:
    driver: bridge
